### ISSUE TITLE
Add support for Azure Resource Manager v2 VMs

### ISSUE THREAD

**Issue by ajhewett** [elastic/elasticsearch-cloud-azure#91] opened 2015-06-08 18:53 UTC
The elasticsearch-cloud-azure plugin node discovery does not work together with VMs created by Azure Resource Manager (ARM) v2.   VMs created by ARM v2 no longer have a CloudService.  Node discovery in elasticsearch-cloud-azure currently needs a CloudService to obtain the IP address of VMs.

**Comment by boynux** [comment] 2015-06-11 06:40
We have same issue with Azure templates V2. Azure templates does not support Cloud Service, hence Discovery does not work as expected.

**Comment by dadoonet** [comment] 2015-06-11 06:44
I don't know anything about azure templates. Can you guys give some examples on what you exactly do so I can try to reproduce the problem and imagine a solution for that case?

**Comment by boynux** [comment] 2015-06-11 06:48
Here is a sample for Elasic cluster: 

https://github.com/Azure/azure-quickstart-templates/blob/master/elasticsearch/data-nodes-2disk-resources.json

The problem with this approach is that master IP addresses are hard coded in implementations and passed to Elastic instance via bash script, which I don't think is scalable and suitable for production use. So the preferred way is Azure Discovery plugin, which didn't work, because new API does not support Cloud Services any more and Microsoft has removed it.

**Comment by dadoonet** [comment] 2015-06-11 07:15
Interesting. I was not aware of it.

I looked at some scripts and it sounds like this template is using unicast, which is good.
This line should inject the correct IP addresses https://github.com/Azure/azure-quickstart-templates/blob/master/elasticsearch/elasticsearch-ubuntu-install.sh#L258

Why do you think it's not good for production usage?

**Comment by boynux** [comment] 2015-06-11 07:59
Because what if you want to add a new node to the cluster? Then you need to re-provision all your cluster VMs I guess. What do you think?

**Comment by dadoonet** [comment] 2015-06-11 08:02
No. The new node just has to be aware of the list of existing IPs. Then when it starts, it will try to ping those master nodes. When one of the master nodes will answer, the current node will be added to the cluster state. The cluster state is then propagated to all master nodes.

So basically this should work fine.

To make sure, could you run a test with 2 nodes at first the add a 3rd one? And see how it goes...

**Comment by ajhewett** [comment] 2015-06-11 08:40
I have used the elasticsearch azure-quickstart-template as a basis.  Setting the unicast IPs does work but I am forced to use static IPs (dynamic IPs might change) which adds complexity.  Replacing nodes get tricky because I have to reuse the same IP addresses or update the unicast addresses on each node.  auto-discovery is so much simpler.

The ARM v2 API makes it easy to get information about resources in a Resource Group.  e.g. to get the list of network addresses associated with the Resource Group "dev-es-cluster" in subscription "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee" call 
https://management.azure.com/subscriptions/aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee/resourceGroups/dev-es-cluster/providers/Microsoft.Network/networkInterfaces?api-version=2015-05-01-preview

Of course, there are some authentication issues to be solved as well.

**Comment by boynux** [comment] 2015-06-11 08:52
@dadoonet Ok, I'll try to do that to see how it's going to work.

**Comment by dadoonet** [comment] 2016-05-25 16:15
I'm unsure about what is needed here.
I'm closing but feel free to reopen in elasticsearch repo with all details if needed.

**Closed by dadoonet** 2016-05-25 16:15 UTC

**Comment by Mpdreamz** [comment] 2016-05-25 16:35
Our elasticsearch azure marketplace offering and ARM template

https://github.com/elastic/azure-marketplace

Uses unicast using hostnames, so the IP's can and in fact are dynamic.

**Comment by dadoonet** [comment] 2016-05-25 16:57
Do you think we should link to that in discovery-azure plugin doc?

**Comment by ThomasArdal** [comment] 2016-06-28 17:01
@Mpdreamz @dadoonet Something needs to be done either way. The discovery plugin doesn't work with VMs created on Azure anymore, since cloud services are no longer a concept when creating VMs. Either remove the discovery plugin from cloud-azure or port it to support resource manager VMs.

I'm aware of the fact the nodes can be configured using unicast IPs or hostnames on Azure, but having a discovery feature in cloud-azure which does not work with the new concepts in Azure doesn't really make sense, or?

**Comment by Mpdreamz** [comment] 2016-06-28 17:22
@ThomasArdal i'm inclined to agree :) It would be nice if the azure plugins played nicely in the arm world. I can see a need to keep the classic (cloud service based) discovery around for those still running clusters in that setting.

@dadoonet what are your thoughts on this? We can still rename the plugin in core to `discovery-azure-classic` and start working on a separate `discovery-azure-arm` plugin.

**Comment by dadoonet** [comment] 2016-06-29 10:33
@Mpdreamz I think that renaming the current plugin to `discovery-azure-classic` in elasticsearch 5.0 makes a lot of sense. I'm +1 we explore the `discovery-azure-arm` path and see where it goes. I don't know it TBH and I hope it's not based on certificates anymore and have a much cleaner SDK than the classic one.

I'm going to propose that in elasticsearch repo.

**Comment by dadoonet** [comment] 2016-06-29 10:45
Definitely I really like the ARM approach: https://github.com/Azure/azure-sdk-for-java#azure-resource-manager-arm-usage

```java
ResourceManagementClient client = new ResourceManagementClientImpl(
    new ApplicationTokenCredentials("client-id", "tenant-id", "secret", null) 
);
client.setSubscriptionId(System.getenv("subscription-id"));
client.setLogLevel(HttpLoggingInterceptor.Level.BODY);

ResourceGroup group = new ResourceGroup();
group.setLocation("West US");
client.getResourceGroups().createOrUpdate("myresourcegroup", group);
```

No more private keys / password...

**Comment by ThomasArdal** [comment] 2016-06-29 16:35
:+1:
