### ISSUE TITLE
Restore snapshot leaves shards unassigned and with CorruptIndexException

### ISSUE THREAD

**Issue by richtmat** [elastic/elasticsearch-cloud-azure#51] opened 2015-01-15 13:59 UTC
I opened an issue (https://github.com/elasticsearch/elasticsearch/issues/9275) but maybe it's more a problem on this plugin side. I'm using Azure blob storage for the snapshots without any special configuration.
When restoring a snapshot, shards are left unassigned and the logs have CorruptIndexException as mentioned in the referenced issue.

**Comment by dadoonet** [comment] 2015-02-18 15:41
@richtmat I tested again today with latest changes and could not reproduce it.

Could you try on your end the same thing?

* remove and install lastest azure plugin:

```
bin/plugin -remove cloud-azure
bin/plugin -install cloud-azure --url https://oss.sonatype.org/content/repositories/snapshots/org/elasticsearch/elasticsearch-cloud-azure/2.5.2-SNAPSHOT/elasticsearch-cloud-azure-2.5.2-20150218.153642-1.zip
```

* backup your index on azure
* restore it

I'm closing for now as I think it's fixed but feel free to reopen if you still have errors.
Could you report here your results?

Note that this version won't help to recover indices which has not been backup'ed correctly.

**Comment by richtmat** [comment] 2015-02-20 13:16
@dadoonet thanks a lot, it works now.

**Comment by dadoonet** [comment] 2015-02-20 13:28
Awesome. Thanks for confirming!

**Comment by tandibar** [comment] 2015-02-25 11:12
I'm sorry, but we are getting the error again. I am a college of @richtmat and tested the restore. Sometimes it works but now we are getting the same error as before:
```
    2015-02-25 11:05:01,040][WARN ][indices.cluster          ] [qa] [some-index][2] failed to start shard
org.elasticsearch.index.gateway.IndexShardGatewayRecoveryException: [some-index][2] failed to fetch index version after copying it over
	at org.elasticsearch.index.gateway.local.LocalIndexShardGateway.recover(LocalIndexShardGateway.java:158)
	at org.elasticsearch.index.gateway.IndexShardGatewayService$1.run(IndexShardGatewayService.java:132)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.lucene.index.CorruptIndexException: [qa_cloud_app_data][2] Preexisting corrupted index [corrupted_zlkVLFWPT3Cn_LHYwl92gw] caused by: CorruptIndexException[verification failed (hardware problem?) : expected=1mvxfgo actual=null writtenLength=47 expectedLength=4792 (resource=name [_2.cfs], length [4792], checksum [1mvxfgo], writtenBy [4.10.2])]
org.apache.lucene.index.CorruptIndexException: verification failed (hardware problem?) : expected=1mvxfgo actual=null writtenLength=47 expectedLength=4792 (resource=name [_2.cfs], length [4792], checksum [1mvxfgo], writtenBy [4.10.2])
	at org.elasticsearch.index.store.Store$VerifyingIndexOutput.verify(Store.java:866)
	at org.elasticsearch.index.store.Store.verify(Store.java:345)
	at org.elasticsearch.index.snapshots.blobstore.BlobStoreIndexShardRepository$RestoreContext.restoreFile(BlobStoreIndexShardRepository.java:842)
	at org.elasticsearch.index.snapshots.blobstore.BlobStoreIndexShardRepository$RestoreContext.restore(BlobStoreIndexShardRepository.java:784)
	at org.elasticsearch.index.snapshots.blobstore.BlobStoreIndexShardRepository.restore(BlobStoreIndexShardRepository.java:162)
	at org.elasticsearch.index.snapshots.IndexShardSnapshotAndRestoreService.restore(IndexShardSnapshotAndRestoreService.java:124)
	at org.elasticsearch.index.gateway.IndexShardGatewayService$1.run(IndexShardGatewayService.java:127)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

	at org.elasticsearch.index.store.Store.failIfCorrupted(Store.java:411)
	at org.elasticsearch.index.store.Store.failIfCorrupted(Store.java:392)
	at org.elasticsearch.index.gateway.local.LocalIndexShardGateway.recover(LocalIndexShardGateway.java:120)
	... 4 more
```
This error is running through the log over and over again...

**Comment by tandibar** [comment] 2015-02-25 15:45
it seems that only the latest snapshot is working... but i will investigate further

**Comment by dadoonet** [comment] 2015-02-25 15:47
Thanks @tandibar 

Wondering if the SNAPSHOT which is failing was created recently (which plugin `2.5.2-SNAPSHOT`) or with an older version.
Is it something you can reproduce. I mean that each time you snapshot same data, restore fails?

Best

**Comment by tandibar** [comment] 2015-02-25 15:57
All snapshots were take with 2.5.2-SNAPSHOT. In the current state i can not restore any other snapshot but the latest. All others (i tried about three or four from 46) have 3 good shards and 7 failing. If I try to restore the latest snapshot into a currently broken index, the restore also failes. If I delete the whole indices and restore the latest snapshot, everything is working again.

**Comment by tandibar** [comment] 2015-02-26 09:37
So, i just made another test:
- Cleared all snapshots
- made initial snapshot
- restored initial snapshot --> everything fine
- deleted some stuff
- made a second snapshot
- restored initial snapshot --> 3 shard successful, 7 failed, log blowing up 
- tried to restore second snapshot --> 3 shard successful, 7 failed, log blowing up 
- deleted both indices
- restore second snapshot --> everything fine (10/10)
- deleted both indices
- restore initial snapshot --> 3 shard successful, 7 failed
- deleted both indices
- restore second snapshot --> nearly fine (8 successfull, 2 failed), log NOT blowing up
- deleted both indices
- restore second snapshot --> everything fine (10/10)

I am clueless what the problem is. What can I do to help you to find this bug. Do you have no problems going back to an older snapshot? Should I try the same with the "fs" adapter to verify that it is in this plugin?

**Comment by dadoonet** [comment] 2015-02-26 09:42
That would be awesome if you could run same test with fs 
And if you could share your dataset somewhere.

Thanks!

**Comment by tandibar** [comment] 2015-02-27 12:38
Same test-setup with fs repository, everything works fine. I will try to create a dataset of our data which fails and has no sensitive data in it.

**Comment by tandibar** [comment] 2015-02-27 13:00
So here is my very basic test setup which fails:

```
# create two indices
curl -XPUT http://localhost:9200/app_index
curl -XPUT http://localhost:9200/asset_index

# add two docs
curl -XPUT http://localhost:9200/app_index/app/1 -d '{ "foo": "bar", "kind": "app" }'
curl -XPUT http://localhost:9200/asset_index/asset/1 -d '{ "foo": "bar", "kind": "asset" }'

# create azure backup repository
curl -XPUT http://localhost:9200/_snapshot/backup-test -d '{ "type": "azure" }'

# create two snapshots 
curl -XPUT http://localhost:9200/_snapshot/backup-test/snapshot-1
curl -XPUT http://localhost:9200/asset_index/asset/2 -d '{ "foo2": "bar2", "kind": "asset" }'
curl -XPUT http://localhost:9200/_snapshot/backup-test/snapshot-2

# list all snapshots
curl -XGET http://localhost:9200/_snapshot/backup-test/_all?pretty

# restore snapshot
curl -XPOST -s http://localhost:9200/_all/_close&pretty=1
curl -XPOST -s http://localhost:9200/_snapshot/backup-test/snapshot-1/_restore?wait_for_completion=true&pretty=1
# => shards are broken
```

**Comment by dadoonet** [comment] 2015-02-27 13:05
Got it! Thanks a lot for the script. Will look and debug soonish!

**Comment by tandibar** [comment] 2015-03-16 13:31
any news on this one?

**Closed** 2015-07-21 20:47 UTC
Labels: bug
